In [1]:

import sys
sys.path.append("..")
import torch
import torch.nn as nn
import torch.nn.functional as F
import xnornet

In [5]:
input = torch.ones(2, 1,14,14) * 2
weight = torch.ones(4,1,3,3) * -2
ref = nn.functional.conv2d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1)
kernel_size = 3
size = input.size()
mean = torch.mean(input.abs(),1, keepdim=True)
k = torch.full((1,1,kernel_size,kernel_size),fill_value=1/(kernel_size**2))
K = nn.functional.conv2d(mean, k, bias=None, stride=1, padding=0, dilation=1, groups=1)
K.size()
a = torch.mean(weight.abs(),(2,3))
a = a.reshape((1,4,1,1))
input = input.sign()
weight = weight.sign()
result = nn.functional.conv2d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1)
result * K * a

tensor([[[[-36., -36., -36.,  ..., -36., -36., -36.],
          [-36., -36., -36.,  ..., -36., -36., -36.],
          [-36., -36., -36.,  ..., -36., -36., -36.],
          ...,
          [-36., -36., -36.,  ..., -36., -36., -36.],
          [-36., -36., -36.,  ..., -36., -36., -36.],
          [-36., -36., -36.,  ..., -36., -36., -36.]],

         [[-36., -36., -36.,  ..., -36., -36., -36.],
          [-36., -36., -36.,  ..., -36., -36., -36.],
          [-36., -36., -36.,  ..., -36., -36., -36.],
          ...,
          [-36., -36., -36.,  ..., -36., -36., -36.],
          [-36., -36., -36.,  ..., -36., -36., -36.],
          [-36., -36., -36.,  ..., -36., -36., -36.]],

         [[-36., -36., -36.,  ..., -36., -36., -36.],
          [-36., -36., -36.,  ..., -36., -36., -36.],
          [-36., -36., -36.,  ..., -36., -36., -36.],
          ...,
          [-36., -36., -36.,  ..., -36., -36., -36.],
          [-36., -36., -36.,  ..., -36., -36., -36.],
          [-36., -36., -36.,  ...

In [8]:
model = xnornet.BinConv2d(1,4,3,bias=False)
input = torch.ones(2,1,14,14) * 2
weight = torch.ones(4,1,3,3) * -4
model.weight = nn.parameter.Parameter(weight)
# print(model.weight)
ref = nn.functional.conv2d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1)
kernel_size = 3
input, K = xnornet.BinActive.apply(input,kernel_size)
# print(K)
model(input,K)

tensor([[[[-72., -72., -72.,  ..., -72., -72., -72.],
          [-72., -72., -72.,  ..., -72., -72., -72.],
          [-72., -72., -72.,  ..., -72., -72., -72.],
          ...,
          [-72., -72., -72.,  ..., -72., -72., -72.],
          [-72., -72., -72.,  ..., -72., -72., -72.],
          [-72., -72., -72.,  ..., -72., -72., -72.]],

         [[-72., -72., -72.,  ..., -72., -72., -72.],
          [-72., -72., -72.,  ..., -72., -72., -72.],
          [-72., -72., -72.,  ..., -72., -72., -72.],
          ...,
          [-72., -72., -72.,  ..., -72., -72., -72.],
          [-72., -72., -72.,  ..., -72., -72., -72.],
          [-72., -72., -72.,  ..., -72., -72., -72.]],

         [[-72., -72., -72.,  ..., -72., -72., -72.],
          [-72., -72., -72.,  ..., -72., -72., -72.],
          [-72., -72., -72.,  ..., -72., -72., -72.],
          ...,
          [-72., -72., -72.,  ..., -72., -72., -72.],
          [-72., -72., -72.,  ..., -72., -72., -72.],
          [-72., -72., -72.,  ...

In [7]:
model.weight

Parameter containing:
tensor([[[[-1., -1., -1.],
          [-1., -1., -1.],
          [-1., -1., -1.]]],


        [[[-1., -1., -1.],
          [-1., -1., -1.],
          [-1., -1., -1.]]],


        [[[-1., -1., -1.],
          [-1., -1., -1.],
          [-1., -1., -1.]]],


        [[[-1., -1., -1.],
          [-1., -1., -1.],
          [-1., -1., -1.]]]], requires_grad=True)